name: "CI"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_releases:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup nix
        uses: cachix/install-nix-action@v22

      - name: OTF files caching
        uses: actions/cache@v2
        with:
          path: fonts
          key: otf-${{ hashFiles('**/hersho_mono.sfd') }}
          restore-keys: |
            otf-

      - name: Build font
        run: |
          if [[ ! -f fonts/HershoMono-Regular.otf ]]; then
            nix develop --command ./scripts/build.sh
          fi

      - name: Lint unpatched font
        run: nix develop --command fontlint fonts/HershoMono-Regular.otf
