name: "CI"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_releases:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup nix
        uses: cachix/install-nix-action@v22

      - name: Build font
        run: ./scripts/build.sh
