name: "CI"
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build_and_releases:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup nix
        uses: cachix/install-nix-action@v22

      - name: OTF files caching
        uses: actions/cache@v2
        with:
          path: fonts
          key: otf-${{ hashFiles('**/*.sfd') }}

      - name: Build fonts
        run: |
          if [[ ! -f fonts/HershoMono-Regular.otf ]]; then
            nix develop --command ./scripts/build.sh
          fi

      - name: Lint unpatched fonts
        run: |
          nix develop --command fontlint fonts/HershoMono-Regular.otf
          nix develop --command fontlint fonts/HershoMono-Italic.otf

      - name: Verify version
        run: |
          FONT_VERSION=$(grep ^Version: hersho_mono.sfd | cut -d " " -f 2 )
          MAJOR=$(echo $FONT_VERSION | cut -d . -f 1 )
          MINOR=$(echo $FONT_VERSION | cut -d . -f 2 | cut -c 1 )
          PATCH=$(echo $FONT_VERSION | cut -d . -f 2 | cut -c 2-3 )
          [[ "$GITHUB_REF_NAME" == "$(printf v%d.%d.%d ${MAJOR} ${MINOR} ${PATCH})" ]]
        if: startsWith(github.ref, 'refs/tags/')

      - name: Create release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            fonts/*.otf
            fonts/*.png
